"""add key lookup table

Revision ID: 0e409f660757
Revises: None
Create Date: 2018-02-21 19:53:26.815851

"""

# revision identifiers, used by Alembic.
revision = '0e409f660757'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_lookup_table',
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_lookup_table')
    # ### end Alembic commands ###
